### PR TITLE
Fix atom freezes while fast cursor move

### LINKED ISSUE #51: Atom freezes while moving fast
When enabled this plugin, atom freezes and does not update screen while repeating up/down key or fast typing.
Please refer this (closed) PR on atom core: atom/atom#6062

### PR DESCRIPTION
**Pull request by ypresto**
Fixes #51

Check `Panel#isVisible` before focus() call which significantly affects
Atom's performance.

### CODE REVIEW

File: lib/atom-ternjs-view-manager.coffee [hunk 1]
```diff
@@ -4,32 +4,33 @@ RenameView = require './atom-ternjs-rename-view'
...
+      @renamePanel.show()
+      return
+    @renameModel = new RenameModel(@manager)
+    @renamePanel = atom.workspace.addBottomPanel item: @renameModel
 
-    hideRename: ->
-        @renamePanel?.hide()
-        @focusEditor()
+  hideRename: ->
+    return unless @renamePanel?.isVisible()
```
Comment (ypresto) [inline lib/atom-ternjs-view-manager.coffee]: This is only meaningful change of this PR.
